---
efiSystemPartition:     "/boot/efi"
efiSystemPartitionSize: 512M
efiSystemPartitionName: EFI
userSwapChoices:
    - none
    - small
    - suspend
    - file

drawNestedPartitions:   false
alwaysShowPartitionLabels: true
allowManualPartitioning:   true
initialPartitioningChoice: none
initialSwapChoice:         none

defaultFileSystemType:  "ext4"
availableFileSystemTypes:  ["ext4","btrfs","xfs","f2fs"]
