---
defaultGroups:
    - wheel
    - audio
    - video
    - storage
    - optical
    - network
    - power

autologinGroup:  autologin

doAutologin:     true

sudoersGroup:    wheel

setRootPassword: true

doReusePassword: true

passwordRequirements:
    minLength: 1
    maxLength: -1

allowWeakPasswords: true

allowWeakPasswordsDefault: true

userShell: /bin/bash

hostname:
  location: EtcFile
  writeHostsFile: true
  template: "sunriseos-${cpu}"
