---
showSupportUrl:         true
showKnownIssuesUrl:     true
showReleaseNotesUrl:    false

requirements:
    requiredStorage:    10.0
    requiredRam:        2.0
    internetCheckUrl:   https://www.archlinux.org
    check:
        - storage
        - ram
        - power
        - internet
        - root
    required:
        - storage
        - ram
        - root
