---
modules-search: [ local ]

instances:
- id:       rootfs
  module:   unpackfs
  config:   unpackfs_rootfs.conf

- id:       vmlinuz
  module:   unpackfs
  config:   unpackfs_vmlinuz.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs@rootfs
  - unpackfs@vmlinuz
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - luksopenswaphookcfg
  - initcpiocfg
  - initcpio
  - removeuser
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - bootloader
  - grubcfg
  - umount
- show:
  - finished

branding: sunriseos

prompt-install: true

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: false

hide-back-and-next-during-exec: false

quit-at-end: false
